
project_id = "qdukcxetdfidgxcuwjdo"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://localhost:5173"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_expiry = 172800
enable_signup = true

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"

[experimental]
pubsub = false
metrics = false

[functions]
[functions.create-checkout]
verify_jwt = true
[functions.check-subscription]
verify_jwt = true
[functions.customer-portal]
verify_jwt = true
[functions.track-usage]
verify_jwt = true
