
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bngejgzcrptylpzyofje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJuZ2VqZ3pjcnB0eWxwenlvZmplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMzY2NjQsImV4cCI6MjA2MTcxMjY2NH0.gcKNqRuALx-E0_v7Y1lSqcl6Z-lZh965WInFR0pxbCo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
