// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdukcxetdfidgxcuwjdo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkdWtjeGV0ZGZpZGd4Y3V3amRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2ODIxOTgsImV4cCI6MjA1NjI1ODE5OH0.DA9H__z42HZ6Qh0Ts4nw4s8zwlfcxYcTsu13pyjDe3Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);